# Generated by Django 5.1.6 on 2025-02-23 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15)),
                ('category', models.CharField(max_length=100)),
                ('experience', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='experts/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profiles_expert_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
